### ISSUE TITLE
Can have better approach?

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-Frontend#590]
![image](https://github.com/tokitou-san/CoreProject-V3-UI/assets/61817579/9732841e-221c-4a47-84aa-82eb45ead93d)

i personally dont like this scroll to reveal logic. Any better ideas?

**Comment by tokitou-san** [comment]
Okay, I think we can do something like
1. Make tippy a bit wider
2. Add status ( like github ) instead email ( email is longer )

**Comment by baseplate-admin** [comment]
> Add status ( like github ) instead email ( email is longer )

That's not gonna fly in. We need to rethink the approach

**Comment by tokitou-san** [comment]
Do you've any designs in mind? well my mind is empty asf

**Comment by baseplate-admin** [comment]
![image](https://github.com/tokitou-san/CoreProject-Frontend/assets/61817579/90322872-7b34-4950-ac1b-db4a0639a049)
