### ISSUE TITLE
add this type of effect for homepage

### ISSUE THREAD

**Issue by baseplate-admin** [tokitou-san/CoreProject-Frontend#754]
https://www.obsbot.com/obsbot-tiny-4k-webcam

**Comment by tokitou-san** [comment]
Yea nice pick, I'm thinking like
add this kinda effect on landing page, I mean fish remains fixed
like uhh "Unlock..." this section ( left-section ) animates on scroll only ( not fish )

how does this sounds to you?

**Comment by tokitou-san** [comment]
Let's discuss homepage related in #689 
Duplicate of #689
